Foo:
  priority: A01
  feature-set: one
  properties:
    - foo_value1
    - foo_value2

Bar:
  priority: A02
  feature-set: one

Baz:
  priority: B01
  feature-set: two
  properties:
    - baz_value1