Foo:
  priority: A01
  feature-set: one
  parameters:
    - name: foo_value1
      property: foo_value1
    - name: foo_value2
      property: foo_value2
  deps:
    - name: something1
      instance: something1-A
      in: A
    - name: something1
      instance: something1-B
      in: B
    - name: something2
      instance: something2-A
      in: A

Bar:
  priority: A02
  feature-set: one

Baz:
  priority: B01
  feature-set: two
  properties:
    - baz_value1